include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
