name: speak_nato
description: Multi-language phonetic alphabet.

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  another_flushbar: ^2.2.4
  flutter_tts: ^4.2.5
  shared_preferences: ^2.2.0
  card_settings: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica.ttf
        - asset: fonts/Helvetica-Bold.ttf
