final Map<String, String> alphabetlocale = {
  "ICAO": "en-US",
  "Swedish": "sv-SE",
  "Ukrainian": "uk-UA",
  "German": "de-DE"
};

final Map<String, Map<String, String>> alphabets = {
  "ICAO": {
    "A": "Alpha",
    "B": "Bravo",
    "C": "Charlie",
    "D": "Delta",
    "E": "Echo",
    "F": "Foxtrot",
    "G": "Golf",
    "H": "Hotel",
    "I": "India",
    "J": "Juliett",
    "K": "Kilo",
    "L": "Lima",
    "M": "Mike",
    "N": "November",
    "O": "Oscar",
    "P": "Papa",
    "Q": "Quebec",
    "R": "Romeo",
    "S": "Sierra",
    "T": "Tango",
    "U": "Uniform",
    "V": "Victor",
    "W": "Whiskey",
    "X": "Xray",
    "Y": "Yankee",
    "Z": "Zulu",
    "0": "Zero",
    "1": "One",
    "2": "Two",
    "3": "Three",
    "4": "Four",
    "5": "Five",
    "6": "Six",
    "7": "Seven",
    "8": "Eight",
    "9": "Nine",
    " ": "Space"
  },
  "Swedish": {
    "A": "Adam",
    "B": "Bertil",
    "C": "Caesar",
    "D": "David",
    "E": "Erik",
    "F": "Filip",
    "G": "Gustav",
    "H": "Helge",
    "I": "Ivar",
    "J": "Johan",
    "K": "Kalle",
    "L": "Ludvig",
    "M": "Martin",
    "N": "Niklas",
    "O": "Olof",
    "P": "Petter",
    "Q": "Qvintus",
    "R": "Rudolf",
    "S": "Sigurd",
    "T": "Tore",
    "U": "Urban",
    "V": "Viktor",
    "W": "Wilhelm",
    "X": "Xerxes",
    "Y": "Yngve",
    "Z": "Zäta",
    "Å": "Åke",
    "Ä": "Ärlig",
    "Ö": "Östen",
    "0": "Nolla",
    "1": "Etta",
    "2": "Tvåa",
    "3": "Trea",
    "4": "Fyra",
    "5": "Femma",
    "6": "Sexa",
    "7": "Sju",
    "8": "Åtta",
    "9": "Nia",
    " ": "Mellanslag"
  },
  "Ukrainian": {
    "А": "Андрі́й",
    "Б": "Богда́н",
    "В": "Васи́ль",
    "Г": "Григо́рій",
    "Ґ": "Ґу́дзик",
    "Д": "Дмитро́",
    "Е": "Ене́й",
    "Є": "Євге́н",
    "Ж": "Жук",
    "З": "Зено́вій",
    "И": "І́грек",
    "І": "Іва́н",
    "Ї": "Їжа́к",
    "Й": "Йо́сип",
    "К": "Кілова́т",
    "Л": "Левко́",
    "М": "Марі́я",
    "Н": "Ната́лка",
    "О": "О́льга",
    "П": "Павло́",
    "Р": "Рома́н",
    "С": "Степа́н",
    "Т": "Тара́с",
    "У": "Украї́на",
    "Ф": "Фе́дір",
    "Х": "Христи́на",
    "Ц": "Центр",
    "Ч": "Чолові́к",
    "Ш": "Шу́ра",
    "Щ": "Щу́ка",
    "Ю": "Ю́рій",
    "Я": "Я́ків",
    "Ь": "Знак",
    "0": "Нуль",
    "1": "Один",
    "2": "Два",
    "3": "Три",
    "4": "Чотири",
    "5": "П'ять",
    "6": "Шість",
    "7": "Сім",
    "8": "Вісім",
    "9": "Дев'ять",
    " ": "Пропуск"
  },
  "German": {
    "A": "Anton",
    "Ä": "Ärger",
    "B": "Berta",
    "C": "Cäsar",
    "D": "Dora",
    "E": "Emil",
    "F": "Friedrich",
    "G": "Gustav",
    "H": "Heinrich",
    "I": "Ida",
    "J": "Julius",
    "K": "Kaufmann",
    "L": "Ludwig",
    "M": "Martha",
    "N": "Nordpol",
    "O": "Otto",
    "Ö": "Ökonom",
    "P": "Paula",
    "Q": "Quelle",
    "R": "Richard",
    "S": "Samuel",
    "T": "Theodor",
    "U": "Ulrich",
    "Ü": "Übermut",
    "V": "Viktor",
    "W": "Wilhelm",
    "X": "Xanthippe",
    "Y": "Ypsilon",
    "Z": "Zacharias",
    "0": "Null",
    "1": "Eins",
    "2": "Zwo",
    "3": "Drei",
    "4": "Vier",
    "5": "Fünf",
    "6": "Sechs",
    "7": "Sieben",
    "8": "Acht",
    "9": "Neun",
    " ": "Leerzeichen",
    ".": "Punkt",
    ",": "Komma",
    ";": "Semikolon",
    ":": "Doppelpunkt",
    "?": "Fragezeichen",
    "!": "Ausrufezeichen",
    "@": "At-Zeichen",
    "&": "Und-Zeichen",
    "\"": "Anführungszeichen",
    "'": "Apostroph",
    "-": "Bindestrich",
    "/": "Schrägstrich",
    "\\": "Umgekehrter Schrägstrich",
    "(": "Runde Klammer links",
    ")": "Runde Klammer rechts",
    "[": "Eckige Klammer links",
    "]": "Eckige Klammer rechts",
    "{": "Geschweifte Klammer links",
    "}": "Geschweifte Klammer rechts",
    "<": "Spitze Klammer links",
    ">": "Spitze Klammer rechts",
    "|": "Senkrechter Strich",
    "°": "Gradzeichen",
    "*": "Sternchen",
    "+": "Pluszeichen",
    "=": "Gleichheitszeichen",
    "#": "Rautenzeichen",
    "§": "Paragraphenzeichen",
    "\$": "Dollarzeichen",
    "€": "Euro-Zeichen",
    "~": "Tilde",
    "_": "Unterstrich",
    "%": "Prozentzeichen",
    "^": "Zirkumflex"
  }
};
